disabled_rules:
  - nesting
  - identifier_name
  - no_fallthrough_only
  - type_name
  - large_tuple
  - line_length
  - shorthand_operator
  - multiple_closures_with_trailing_closure
  - closure_parameter_position
  - unused_optional_binding

  # 暫時移除
  # - todo
  - function_body_length


included:
  - YumeKit

file_length:
  warning: 600
  error: 1200

type_name:
  excluded: 
    - TC

identifier_name:
  excluded: # excluded via string array
    - mo
    - vc
    - cd
    - id
    - pb
    - en
    - to

    - tc
    # - ch
    # - pd
    # - yl
    # - km
    # - tt
    # - cy

    - and
    - or
    - in

    